### ISSUE TITLE
Directory.copy() crashes when dir already exists

### ISSUE THREAD

**Issue by atasak** [dsherret/ts-simple-ast#196]
When saving source files from a directory as described in #182 #185, a crash happens. From #182:

```typescript
const genSrc = ast.getDirectoryOrThrow("genSrc");
const genDist = genSrc.copy("../genDist");

// do manipulations on genDist's source files here

await genDist.saveUnsavedSourceFiles();

const result = await genDist.emit({
    declarationDir: "../genSrc",
    outDir: "../../dist/genDist"
});
// if you need the emitted file paths, they exist in result.getOutputFilePaths()
```

This crashes if `root.genDist` does already exist: 

```
Error: A directory already exists at the provided path: root/genDir
    at InvalidOperationError.BaseError [as constructor] (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/errors/BaseError.js:16:28)
    at new InvalidOperationError (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:17:28)
    at CompilerFactory.createDirectory (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:274:19)
    at CompilerFactory.getOrCreateDirectory (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:289:57)
    at Directory.copy (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/fileSystem/Directory.js:480:53)
    at ast.forgetNodesCreatedInBlock.remember (/home/niek/projects/projects/apione/dist/compiler/compiler/schemer.js:23:31)
    at CompilerFactory.forgetNodesCreatedInBlock (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:400:13)
    at TsSimpleAst.forgetNodesCreatedInBlock (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/TsSimpleAst.js:390:37)
    at Schemer.extractSources (/home/niek/projects/projects/apione/dist/compiler/compiler/schemer.js:20:18)
    at Schemer.run (/home/niek/projects/projects/apione/dist/compiler/compiler/schemer.js:13:14)
```

Note: I only tested this with `genDir.saveUnsavedSourceFilesSync()` because of #194.

**Comment by dsherret** [comment]
Seems like it's crashing on `copy` though?

**Comment by atasak** [comment]
Yes, you're right. Sorry...

**Comment by dsherret** [comment]
This will also be fixed in v5. Thanks for finding all the kinks with this feature @atasak! I'm sorry they existed in the first place though...

**Comment by atasak** [comment]
No problem. I understand it's still all WIP and I'm just really happy the project exists and gets fixed :)

**Comment by atasak** [comment]
In version 5.0.0, the bug still exists, but it now crashes on already existing source files instead of the directory...

```
(node:5576) UnhandledPromiseRejectionWarning: Error: A source file already exists at the provided file path: root/genDist/tests.ts
    at InvalidOperationError.BaseError [as constructor] (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/errors/BaseError.js:16:28)
    at new InvalidOperationError (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:17:28)
    at CompilerFactory.createSourceFileFromText (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:151:19)
    at SourceFile.copy (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/compiler/file/SourceFile.js:169:44)
    at Directory.copy (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/fileSystem/Directory.js:507:28)
    at ast.forgetNodesCreatedInBlock.remember (/home/niek/projects/projects/apione/src/compiler/compiler/schemer.ts:32:31)
    at CompilerFactory.<anonymous> (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:419:34)
    at step (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:32:23)
    at Object.next (/home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:13:53)
    at /home/niek/projects/projects/apione/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:7:71
```

**Comment by dsherret** [comment]
@atasak that's currently by design to prevent overwrites, but I just did a quick v5.1.0 release to add an overwrite option. Do the following:

```ts
dir.copy("../newDir", { overwrite: true }); // won't throw anymore
```

Also, if using the previous code and running it, the error message should ask you if you meant to use the overwrite option.

Let me know if you have any issues with this. Thanks!
