### ISSUE TITLE
"typeRoots" option is ignored

### ISSUE THREAD

**Issue by osyrisrblx** [dsherret/ts-simple-ast#415]
In tsconfig.json, the compilerOptions.types option seems to be ignored by ts-simple-ast.

ts-simple-ast API doesn't seem to get any type info from .d.ts files outside of the source root directory when using "types" option.

**Comment by osyrisrblx** [comment]
@dsherret looks like if a .d.ts file is outside of the "rootDir", all of the defined types are picked up by ts-simple-ast as type "any".

Attempting to use `Type.getSymbol();` returns `undefined` as well.

VSCode's built-in TypeScript seems to understand the types just fine which makes me think it's a ts-simple-ast bug.

**Comment by dsherret** [comment]
@osyrisrblx how are you specifying the `types` compiler option in ts-simple-ast? I'll take a look soon.

**Comment by osyrisrblx** [comment]
@dsherret My tsconfig.json looks like this:
```JSON
{
	"compilerOptions": {
		"strict": true,
		"outDir": "out",
		"rootDir": "src",
		"baseUrl": "src",
		"downlevelIteration": true,
		"noLib": true,
		"target": "ES5",
		"types": [
			"types",
		]
	}
}```

where "types" is a folder inside the same directory as "src" and "out".

I've also tried replacing `"types"` with `"types/"`, `"types/*"`, and `"types/**/*"`

**Comment by dsherret** [comment]
@osyrisrblx are you specifying to use the `tsconfig.json`?

**Comment by osyrisrblx** [comment]
@dsherret Yes, I supply a path to it when I create a Project object.

You can find the code here if it helps:
https://github.com/roblox-ts/roblox-ts/blob/master/src/class/Compiler.ts#L22

FWIW, I've been able to read properties like `"baseUrl"` from `Project.getCompilerOptions()`.

**Comment by dsherret** [comment]
@osyrisrblx ok thanks! Just making sure :)

**Comment by dsherret** [comment]
You will want to use the "typeRoots" option and not "types". Read more here: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

There was a bug with "typeRoots" not working though. That's fixed now in 14.4.3.

**Comment by osyrisrblx** [comment]
@dsherret Unfortunately, it looks like I 🎉'd prematurely. This bug is still occurring for me, and I made a small repro to demonstrate it with 14.4.3:

https://github.com/osyrisrblx/415-repro

**Comment by dsherret** [comment]
@osyrisrblx I was looking into this and the `typeRoots` option is not relevant in that situation. For example, when the `typeRoots` option is removed it will still work. I think perhaps `tsc` is being a bit generous in what it includes, but I'm not sure why. Perhaps it includes all `.d.ts` files regardless of the `rootDir`.

`typeRoots` is supposed to work on packages like `@types` packages (see [here](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types)) and so it doesn't search for files in the directory specified.

For example, to see the true behaviour of `typeRoots`:

1. Move the typings folder up a directory so its a sibling of `test-project`. Then change `typeRoots` to `"typeRoots": ["../typings"]`. Run `tsc` and observe the compile error that it can't find `Foo`.
2. Then create a sub folder called `foo` and move `foo.d.ts` into it. Rename `foo.d.ts` to `index.d.ts`. Run `tsc` and see it compiles now.

If anything, perhaps this library should include all `.d.ts` files in the directory and sub directories of `tsconfig.json`, but I'm unsure if that's how `tsc` actually works. I'd need to look into it more.
